<a href="https://colab.research.google.com/github/sayymon/machine-learning/blob/master/Aula_1_Algoritimos_n%C3%A3o_supervisionados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import pandas as pd

uri = 'https://raw.githubusercontent.com/alura-cursos/machine-learning-algoritmos-nao-supervisionados/master/movies.csv'
filmes = pd.read_csv(uri)

filmes.columns = ['idFilme','titulo','generos']

filmes.head()

   idFilme  ...                                      generos
0        1  ...  Adventure|Animation|Children|Comedy|Fantasy
1        2  ...                   Adventure|Children|Fantasy
2        3  ...                               Comedy|Romance
3        4  ...                         Comedy|Drama|Romance
4        5  ...                                       Comedy

[5 rows x 3 columns]

In [15]:
#Recupera as condições binarias de um dado de tipo texto
generos = filmes.generos.str.get_dummies()

generos.head()

pd.concat([filmes,generos],axis=1)

      idFilme                                     titulo  ... War  Western
0           1                           Toy Story (1995)  ...   0        0
1           2                             Jumanji (1995)  ...   0        0
2           3                    Grumpier Old Men (1995)  ...   0        0
3           4                   Waiting to Exhale (1995)  ...   0        0
4           5         Father of the Bride Part II (1995)  ...   0        0
...       ...                                        ...  ...  ..      ...
9737   193581  Black Butler: Book of the Atlantic (2017)  ...   0        0
9738   193583               No Game No Life: Zero (2017)  ...   0        0
9739   193585                               Flint (2017)  ...   0        0
9740   193587        Bungo Stray Dogs: Dead Apple (2018)  ...   0        0
9741   193609        Andrew Dice Clay: Dice Rules (1991)  ...   0        0

[9742 rows x 23 columns]